### ISSUE TITLE
Protosintesis y Carga Cuark no funcionan exactamente igual que en los juegos oficiales.

### ISSUE THREAD

**Issue by ClaraDragon** [PokeLiberty/Essentials-BES#13]
Protosintesis y Carga Cuark no funcionan exactamente igual que en los juegos oficiales.

**Comment by albertomcastro4** [comment]
En que difiere exactamente el comportamiento del oficial?

**Comment by ClaraDragon** [comment]
> En que difiere exactamente el comportamiento del oficial?

En lugar de un buff al stat(como si llevase un item potenciador), como en los juegos oficiales, te sube un stat directamente. 
La activación tampoco funciona correctamente porque hace cosas un poco raras con el clima/campo y la energia potenciadora.

**Comment by albertomcastro4** [comment]
Ver Pull Request #16. Recomiendo testear bien la habilidad antes de hacer el merge. 
Hay que testear:
- [x] La habilidad se activa al entrar en combate ya existiendo el clima/campo.
- [x] La habilidad se activa cuando se pone el clima/campo ya estando en combate.
- [x] La habilidad solo gasta el objeto `Booster Energy` si no se dan las condiciones para activarse con naturalidad.
- [ ] La stat elegida es la correcta, teniendo en cuenta cambios de stats, [pero no objetos equipados](https://bulbapedia.bulbagarden.net/wiki/Quark_Drive_(Ability))
- [ ] Los multiplicadores de stats se aplican correctamente.
- [ ] El orden de las stats en caso de empate sigue el [original](https://bulbapedia.bulbagarden.net/wiki/Quark_Drive_(Ability)#Effect).
- [x] `Transformación` e `Impostor` no deben copiar el efecto.
- [x] El efecto acaba cuando se acaba el campo/clima o el Pokémon es cambiado.

**Comment by albertomcastro4** [comment]
Hace falta implementar:
- [x] Las habilidades `Cloud Nine` y `Air Lock` deben impedir la activación natural de `Protosynthesis`. Si la habiliadad ya se encontraba activada, se debe desactivar salvo que se activase mediante el uso de `Booster Energy`.
- [x] La habilidad `Moldbreaker` debe ignorar el aumento de defensa de `Protosynthesis` y `Quark Drive`.
- [x] El clima `HARSHSUN` debe activar `Protosynthesis`.
