### ISSUE TITLE
Dado Trucado no está programado

### ISSUE THREAD

**Issue by ClaraDragon** [PokeLiberty/Essentials-BES#14]
El Dado trucado no está programado

**Comment by albertomcastro4** [comment]
Ver Pull Request #15. 
- [x] Dado Trucado asegura 4 o 5 hits en los ataques clásicos (ataques con función `0x0C0`).
- [x] Dado Trucado hace que `Triple Patada` y `Triple Axel` solo comprueben una vez la precisión.
- [x] Dado Trucado hace que `Proliferación` golpee al menos 4 veces, y luego comprueba precisión para el resto de hits (no sé si es exactamente el comportamiento oficial)
- [x] Gráfico de Dado Trucado (desconozco si esta actualizado en la release, pero no lo tengo en mi versión)
